[package]
name = "patch-db-macro"
version = "0.1.0"
authors = ["Aiden McClelland <me@drbonez.dev>"]
edition = "2018"
description = "macros for defining typed patch dbs"
license = "MIT"
repository = "https://github.com/Start9Labs/patch-db"

[lib]
proc-macro = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
patch-db-macro-internals = { path = "../patch-db-macro-internals" }
syn = "1.0.62"
proc-macro2 = "1.0.1"
